/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SessionRequest } from '../../models/session-request';
import { SessionResponse } from '../../models/session-response';

export interface AddSession$Params {
      body: SessionRequest
}

export function addSession(http: HttpClient, rootUrl: string, params: AddSession$Params, context?: HttpContext): Observable<StrictHttpResponse<SessionResponse>> {
  const rb = new RequestBuilder(rootUrl, addSession.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SessionResponse>;
    })
  );
}

addSession.PATH = '/sessions';
