/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { KindResponse } from '../../models/kind-response';

export interface GetKindById$Params {
  id: number;
}

export function getKindById(http: HttpClient, rootUrl: string, params: GetKindById$Params, context?: HttpContext): Observable<StrictHttpResponse<KindResponse>> {
  const rb = new RequestBuilder(rootUrl, getKindById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<KindResponse>;
    })
  );
}

getKindById.PATH = '/kinds/{id}';
