services:
  postgres:
    container_name: postgres-scolaire
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: scolaire-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - scolaire-ms
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d scolaire-db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    networks:
      - scolaire-ms

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    networks:
      - scolaire-ms
    depends_on:
      - keycloak-mysql
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8181/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  scolaire-api:
    image: scolaire-api
    ports:
      - "8092:8092"
    environment:
      - DB_HOST=postgres-scolaire
      - DB_PORT=5432
      - DB_NAME=scolaire-db
      - DB_USERNAME=username
      - DB_PASSWORD=password
    #      - KEYCLOAK_URL=http://keycloak:8181
    #      - KEYCLOAK_REALM=scolaire-ms
    depends_on:
      - postgres
    #      - keycloak
    networks:
      - scolaire-ms
  ###
  scolaire-front:
    image: scolaire-front
    #    build:
    #      context: ./scolaire-front
    #      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - KEYCLOAK_URL=http://keycloak:8181
      - KEYCLOAK_REALM=scolaire-ms
      - KEYCLOAK_CLIENT_ID=scolaire-ms-app
    networks:
      - scolaire-ms
    depends_on:
      - scolaire-api
      - keycloak

networks:
  scolaire-ms:
    driver: bridge

volumes:
  postgres_data:
    driver: local
