/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SectorRequest } from '../../models/sector-request';
import { SectorResponse } from '../../models/sector-response';

export interface AddKind$Params {
      body: SectorRequest
}

export function addKind(http: HttpClient, rootUrl: string, params: AddKind$Params, context?: HttpContext): Observable<StrictHttpResponse<SectorResponse>> {
  const rb = new RequestBuilder(rootUrl, addKind.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SectorResponse>;
    })
  );
}

addKind.PATH = '/sectors';
