/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SectorResponse } from '../../models/sector-response';

export interface GetSectorById$Params {
  id: number;
}

export function getSectorById(http: HttpClient, rootUrl: string, params: GetSectorById$Params, context?: HttpContext): Observable<StrictHttpResponse<SectorResponse>> {
  const rb = new RequestBuilder(rootUrl, getSectorById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SectorResponse>;
    })
  );
}

getSectorById.PATH = '/sectors/{id}';
