/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseAdministrativeAgentResponse } from '../../models/page-response-administrative-agent-response';

export interface ListAllAdminAgents$Params {
  page?: number;
  size?: number;
}

export function listAllAdminAgents(http: HttpClient, rootUrl: string, params?: ListAllAdminAgents$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseAdministrativeAgentResponse>> {
  const rb = new RequestBuilder(rootUrl, listAllAdminAgents.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseAdministrativeAgentResponse>;
    })
  );
}

listAllAdminAgents.PATH = '/agents/by-page';
