/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { TeachersService } from './services/teachers.service';
import { SubjectsService } from './services/subjects.service';
import { StudentsService } from './services/students.service';
import { SessionsService } from './services/sessions.service';
import { SectorsService } from './services/sectors.service';
import { RegistrationsService } from './services/registrations.service';
import { ProgramsService } from './services/programs.service';
import { KindsService } from './services/kinds.service';
import { HalfYearlyService } from './services/half-yearly.service';
import { CoursesService } from './services/courses.service';
import { ClassesService } from './services/classes.service';
import { AdministrativeAgentService } from './services/administrative-agent.service';
import { AcademieYearsService } from './services/academie-years.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    TeachersService,
    SubjectsService,
    StudentsService,
    SessionsService,
    SectorsService,
    RegistrationsService,
    ProgramsService,
    KindsService,
    HalfYearlyService,
    CoursesService,
    ClassesService,
    AdministrativeAgentService,
    AcademieYearsService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
