/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AcademieYearRequest } from './models/academie-year-request';
export { AcademieYearResponse } from './models/academie-year-response';
export { AdministrativeAgentRequest } from './models/administrative-agent-request';
export { AdministrativeAgentResponse } from './models/administrative-agent-response';
export { ClasseRequest } from './models/classe-request';
export { ClasseResponse } from './models/classe-response';
export { CourseRequest } from './models/course-request';
export { CourseResponse } from './models/course-response';
export { HalfYearlyRequest } from './models/half-yearly-request';
export { HalfYearlyResponse } from './models/half-yearly-response';
export { KindRequest } from './models/kind-request';
export { KindResponse } from './models/kind-response';
export { PageResponseAcademieYearResponse } from './models/page-response-academie-year-response';
export { PageResponseAdministrativeAgentResponse } from './models/page-response-administrative-agent-response';
export { PageResponseClasseResponse } from './models/page-response-classe-response';
export { PageResponseCourseResponse } from './models/page-response-course-response';
export { PageResponseHalfYearlyResponse } from './models/page-response-half-yearly-response';
export { PageResponseKindResponse } from './models/page-response-kind-response';
export { PageResponseProgramResponse } from './models/page-response-program-response';
export { PageResponseRegistrationResponse } from './models/page-response-registration-response';
export { PageResponseSectorResponse } from './models/page-response-sector-response';
export { PageResponseSessionResponse } from './models/page-response-session-response';
export { PageResponseStudentResponse } from './models/page-response-student-response';
export { PageResponseSubjectResponse } from './models/page-response-subject-response';
export { PageResponseTeacherResponse } from './models/page-response-teacher-response';
export { ProgramRequest } from './models/program-request';
export { ProgramResponse } from './models/program-response';
export { RegistrationRequest } from './models/registration-request';
export { RegistrationResponse } from './models/registration-response';
export { SectorRequest } from './models/sector-request';
export { SectorResponse } from './models/sector-response';
export { SessionRequest } from './models/session-request';
export { SessionResponse } from './models/session-response';
export { StudentRequest } from './models/student-request';
export { StudentResponse } from './models/student-response';
export { SubjectRequest } from './models/subject-request';
export { SubjectResponse } from './models/subject-response';
export { TeacherRequest } from './models/teacher-request';
export { TeacherResponse } from './models/teacher-response';
