/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { TeachersService } from './services/teachers.service';
export { SubjectsService } from './services/subjects.service';
export { StudentsService } from './services/students.service';
export { SessionsService } from './services/sessions.service';
export { SectorsService } from './services/sectors.service';
export { RegistrationsService } from './services/registrations.service';
export { ProgramsService } from './services/programs.service';
export { KindsService } from './services/kinds.service';
export { HalfYearlyService } from './services/half-yearly.service';
export { CoursesService } from './services/courses.service';
export { ClassesService } from './services/classes.service';
export { AdministrativeAgentService } from './services/administrative-agent.service';
export { AcademieYearsService } from './services/academie-years.service';
