/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TeacherResponse } from '../../models/teacher-response';

export interface AssignCourseToTeacher$Params {
  teacherId: number;
  courseId: number;
}

export function assignCourseToTeacher(http: HttpClient, rootUrl: string, params: AssignCourseToTeacher$Params, context?: HttpContext): Observable<StrictHttpResponse<TeacherResponse>> {
  const rb = new RequestBuilder(rootUrl, assignCourseToTeacher.PATH, 'post');
  if (params) {
    rb.path('teacherId', params.teacherId, {});
    rb.path('courseId', params.courseId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TeacherResponse>;
    })
  );
}

assignCourseToTeacher.PATH = '/teachers/{teacherId}/assign-course/{courseId}';
