/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CourseRequest {
  academieYearId?: number;
  archive?: boolean;
  classeId: number;
  description?: string;
  halfYearlyId?: number;
  id?: number;
  name: string;
  subjectId: number;
}
