/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HalfYearlyResponse } from '../models/half-yearly-response';
export interface PageResponseHalfYearlyResponse {
  content?: Array<HalfYearlyResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
