/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AcademieYearResponse } from '../models/academie-year-response';
export interface PageResponseAcademieYearResponse {
  content?: Array<AcademieYearResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
