/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdministrativeAgentResponse } from '../models/administrative-agent-response';
export interface PageResponseAdministrativeAgentResponse {
  content?: Array<AdministrativeAgentResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
