/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationResponse {
  academieYearId?: number;
  administrativeAgentId?: number;
  archive?: boolean;
  classeId?: number;
  date?: string;
  description?: string;
  id?: number;
  programId?: number;
  studentId?: number;
  studentFistName?: string;
  studentLastName?: string;
  registrationNu?: string;
  administrativeFirstName?: string;
  administrativeLastName?: string;
  classeName?: string;
  programName?: string;
  academieName?: string;
}
