/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionRequest {
  archive?: boolean;
  bigInDate: string;
  courseId?: number;
  description?: string;
  endDate?: string;
  id?: number;
  name: string;
  teacherId?: number;
}
